# Generated by Django 4.0.3 on 2022-05-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovnis_api', '0002_alter_sighting_continent_alter_sighting_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='descripcion',
            new_name='description',
        ),
    ]
