# Generated by Django 4.0.3 on 2022-09-01 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ovnis_api', '0003_rename_descripcion_sighting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=300)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovnis_api.sighting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
